### ISSUE TITLE
[Bug] Пачка багов с OverlaySource

### ISSUE THREAD

**Issue by tonygks** [iXab3r/EyeAuras#15]
1. Не сохраняет в файл настроек название окна если процесс был указан вручную только через выпадающее меню(вытекает из второго пункта).
2. Сохраняет в файл настроек текст введенный в строку "названия окна", а не название найденного окна. 
3. При закрытии источника ищет новый процесс подходящий по названию(в случае с "Lost ark" и т.д. с некоторой долей вероятности найдет браузер с открытым сайтом по ЛА к примеру). Напрашивается привязка к окну по window class name или названию процесса.

4.
a) Частный случай при указании хрома в виде источника, при переключении табы в хроме изменяется название окна, но софт не обновляет данные об этом процессе в этом случае(по идее бессмысленно это править, но так на всякий случай). 
б) Ну и туда же - не обновляется название окна процесса при клонировании ауры с хромом в виде источника(в принципе понятно откуда растут ноги, но возможно где то еще повлияет).

**Comment by iXab3r** [comment]
Завел багу насчет смены названия - https://github.com/iXab3r/EyeAuras/issues/19

Проблему с сохранением выбора пофиксил, завел новый тикет на доработку WindowSelector'а - https://github.com/iXab3r/EyeAuras/issues/18
