### ISSUE TITLE
[Bug] Active Window Trigger

### ISSUE THREAD

**Issue by tonygks** [iXab3r/EyeAuras#16]
Создаем ауру, добавляем триггер, указываем окно в триггере, закрываем окно.
Название окна в триггере пропадает => аура перманентно не работает. 

В итоге если закрыть процесс указанный в триггере до закрытия EyeAuras, то сохранение новых аур произойдет с неработающим триггером.

**Comment by iXab3r** [comment]
Поправлено в 70+, но  пришлось пока пожертвовать комбо боксами, теперь там кнопка для выбора окна - впоследстии нужно переписать на AutoCompleteTextBox
