### ISSUE TITLE
Не синхронизирована иконка замка. Сетка ауры.

### ISSUE THREAD

**Issue by tonygks** [iXab3r/EyeAuras#17]
По идее закрытый замок должен означать залоченный ресайз. Сбивает с толку.
**Ну и имхо кнопка Locked/Unlocked выглядела бы понятнее.**
https://i.imgur.com/4ADqlOz.png

Повторюсь - "сетка" при выборе зоны захвата и при unlocke сильно мешает точно подобрать размеры т.к. через нее плохо видно. Ее сброс правым кликом скрывает конфиг меню ауры. 

**В режиме анлока я бы убрал "сетку" и возможно сделал уголок за который тянуть каким нибудь более якрим цветом(желтым к примеру - он есть в интерфейсе при отключении ауры ), чтобы было видно какие ауры не залочены.**

**От "сетки" в режиме выбора зоны захвата я бы тоже отказался.** Возможно вернул бы "open config" т.к. единственный вариант подправить зону захвата настроенной ауры это:
- нажать выбрать регион
- наблюдать "сетку"
- наблюдать зеленый контур области захвата, который остается в области ауры
- править в таком виде зону захвата через конфиг стрелками

**Вывод:** плохо видно и хочется выбрать зону захвата по новой, но это ничего не изменит т.к. сетка и зеленый контур останутся и подгонять размеры через edit box'ы все равно придется в условиях плохой видимости.

**Comment by iXab3r** [comment]
1) Добавил лок/анлок кнопки
2) Сетка теперь видна только если мышь наведена на окно оверлея

От сетки пока отказываться не хочется - мне, к примеру, гораздо удобнее с сеткой "прицеливаться", возможно я не одинок, надо будет поспрашивать

**Comment by iXab3r** [comment]
поправлено
